project:
  type: book
  output-dir: docs

book:
  title: "Unsupervised Machine Learning"
  author: "Michael Foley"
  date: today
  cover-image: images/unsupervised-ml.jpg
  chapters:
    - index.qmd
    - 01-cluster-analysis.qmd
    - 02-pca.qmd
    - 03-references.qmd

bibliography: references.bib

execute: 
  echo: true
  message: false
  error: false
  warning: false

format:
  html:
    theme: cosmo
    toc-title: "On this page"
    toc-depth: 4
    code-tools: true
    code-overflow: scroll
    code-fold: false
    fig-cap-location: top

editor: source

language: 
  code-summary: "Show the code"
